module Z
  VERSION = "0.1.0"
end

require "./z/error"
require "./z/checksums/adler32"
require "./z/checksums/crc32"
require "./z/bits/bit_reader"
require "./z/bits/bit_writer"
require "./z/huffman/tables"
require "./z/huffman/tree"
require "./z/huffman/encoder"
require "./z/deflate/deflate"
require "./z/deflate/inflate"
require "./z/deflate/reader"
require "./z/deflate/lz77"
require "./z/deflate/block_writer"
require "./z/deflate/writer"
require "./z/zlib/zlib"
require "./z/zlib/reader"
require "./z/zlib/writer"
require "./z/gzip/gzip"
require "./z/gzip/header"
require "./z/gzip/reader"
require "./z/gzip/writer"
